### PR TITLE
Feature/issue 14/open in system tray

### PR DESCRIPTION
**Pull request by ioki9**
Implementation of SystemTrayManager class. The class purpose is to bind to a main window of a program and manage tray icon of that window.

I have a question implementation wise. Do you see your app using multiple tray icons? Because I can implement the class in different ways. I was thinking of a singleton pattern in case you will ever need only one tray icon or I can do it the way it will be able to create multiple tray icons for different windows (I will probably have to make a more general class then). So let me know which of those you see more fit for your app, thanks.

### CODE REVIEW

**Comment by ioki9** [comment]
Oh, and about the multiple tray icons, I am not 100%  sure if my idea will work, so don't take it for granted.

**Comment by hetulbhatt** [comment]
hello @ioki9, I am not able to compile your code. What command do you use for compilation?

I use: `g++ -std=c++17 src/main.cpp`

getting the following error while compiling your code: 
[err.txt](https://github.com/hetulbhatt/KeyFlow/files/11878337/err.txt)

**Comment by ioki9** [comment]
> hello @ioki9, I am not able to compile your code. What command do you use for compilation?
> 
> I use: `g++ -std=c++17 src/main.cpp`
> 
> getting the following error while compiling your code: [err.txt](https://github.com/hetulbhatt/KeyFlow/files/11878337/err.txt)

Sorry, I forgot to mention you need to link Gdi32 library for some functions to work. ( -lGdi32)

**Comment by hetulbhatt** [comment]
Okay, thanks.

**Comment by ioki9** [comment]
Oh, you have std mutex/thread errors. May I ask what compiler are you using? If you use mingw then I think you need a version with POSIX threads for std mutex/threads to work. I can rewrite that with winapi threads instead of std if you want, although I never used them before,

**Comment by hetulbhatt** [comment]
Actually i am AFK currently, will check the posix version once i get back. Until then, i just wanted to convey the plan that i have already made an issue to start with the GUI interface of this software - so it's already on the roadmap. Now, I believe, with whatever lightweight GUI library we use, we will get some API to make the program run in background - either accessible in the tray or in the task manager. Due to which I think, we can focus on GUI part first, and incorporate this change with that.

**Comment by hetulbhatt** [comment]
@ioki9, first of all, thank you so much for your contribution. I couldn't test it previously as my version of MinGW g++ didn't support threads and mutex, which is why I migrated my project from g++-based compilation to cl (MSVC)-based compilation locally. By doing so, I was able to compile your source code correctly, after making some amendments, of course.

While testing, I noticed that your implementation minimizes the window automatically when it loses focus, which is a clever solution. However, it can still be annoying for the user who may see the program running in the taskbar. Taking these factors into consideration, I won't be able to merge this pull request. Please let me know your thoughts.

**Comment by ioki9** [comment]
@hetulbhatt Behavior of window minimization on focus loss (when you click somewhere else) is a default Windows behavior. Maybe I am not understanding you correctly and you mean window hiding. If so then I haven't written the code for such behavior and I don't get it this behavior on my machine. Can you explain in more details what do you mean?

**Comment by ioki9** [comment]
1) Focus on your app.
2) I pressed on vscode, focus is on vscode, your window is not minimized.
image
image

**Comment by hetulbhatt** [comment]
Closing this pull request due to merge conflicts. Thanks @ioki9 for your efforts. If you are still interested in this project, you can check this spike: https://github.com/hetulbhatt/KeyFlow/issues/18

**Pull request closed without merging**
